### ISSUE TITLE
Add installation instructions?

### ISSUE THREAD

**Issue by jhrcek** [ad-si/Brillo#17]
Hello,
thanks for "resurrecting" gloss!
I want to pickup this package for some weekend hacking fun :)
While building it on fedora, I found I'm missing some native dependencies to make it build.

Do you think there's a place in a readme (or perhaps in separate installation.md text file)
to add OS-specific installation / requirements instructions as like this?

#### Fedora
```bash
sudo dnf install glfw-devel libXxf86vm-devel
```

**Comment by ad-si** [comment]
Good idea! Added it in 83aa11a. If the section is getting too long, we can move it somewhere else later.
